name: cryphub
description: An app to see latest information about crypto currencies.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  kt_dart: ^0.10.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  infinite_scroll_pagination: ^3.1.0
  injectable: ^1.5.0
  cached_network_image: ^3.2.0
  gap: ^2.0.0
  palette_generator: ^0.3.2
  get_storage: ^2.0.3
  top_snackbar_flutter: ^1.0.2
  hive_flutter: ^1.1.0
  logger: ^1.1.0
  dio_cache_interceptor: ^3.2.2
  dio_cache_interceptor_hive_store: ^3.1.0
  auto_route: ^3.2.1
  shared_preferences: ^2.0.12
  path_provider: ^2.0.8
  path: ^1.8.0
  after_layout: ^1.1.0
  theme_provider: ^0.5.0

dev_dependencies:

  auto_route_generator: ^3.2.1
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  http_mock_adapter: ^0.3.2
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.3
  mockito: ^5.0.17



flutter:

  uses-material-design: true

